Add Fleet & Agent 8.16.0 Release Notes
elastic/ingest-docs pull request #1412
Opened 2024-10-29 17:58 UTC by kilfoyle

DRAFT

This adds the 8.16.0 Fleet & Elastic Agent Release Notes:

* Fleet contents from [Kibana Release Notes PR](https://github.com/elastic/kibana/pull/198166)
* Fleet Server contents from [BC2 changelog](https://github.com/elastic/fleet-server/tree/d1e230a3f02e63c34fc9dfee4bc2d0dd3f97303a/changelog/fragments)
* Elastic Agent contents from [BC2 "core" changelog](https://github.com/elastic/elastic-agent/tree/df43442062f2e76a5b630cd71b5ccb74e9dfd809/changelog/fragments)

See [DOCS PREVIEW - TBD]()

Closes: https://github.com/elastic/ingest-docs/issues/1411

2024-11-05 21:25 UTC, cmacknz commented on docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
> +* Add agentless UX creation flow. {kibana-pull}189932[#189932]
@kpollich do we want anything to do with agentless in the release notes yet, considering it isn't usable or really announced yet?

2024-11-05 21:26 UTC, cmacknz commented on docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
> +* Add `/api/fleet/agents/:id/audit/unenroll` API that an {agent} or Endpoint process may use to enable accurate status reporting in the {fleet} UI. {fleet-server-pull}3818[#3818] {agent-issue}484[#48
```suggestion
* Add `/api/fleet/agents/:id/audit/unenroll` API that an {agent} or Endpoint process may use to report that an agent was uninstalled or unenrolled to {fleet}. {fleet-server-pull}3818[#3818] {agent-issue}484[#484]
```

2024-11-05 21:26 UTC, cmacknz commented on docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
> +* Remove support for the experimental shippers feature. Removal is non-breaking since the feature was experimental only. {agent-pull}5308[#5308] {agent-issue}4547[#4547]
```suggestion
* Remove support for the experimental shippers feature. {agent-pull}5308[#5308] {agent-issue}4547[#4547]
```

2024-11-05 21:56 UTC, kilfoyle commented
@cmacknz As you suggested in the feature summary issue, I've added in descriptions from that issue for the release features, in commit [9323922](https://github.com/elastic/ingest-docs/pull/1412/commits/9323922dc3ecdb2797281d488c53100e027b47e1).

The "installing agent using Helm" feature wasn't in the release notes originally, I think because [the PR](https://github.com/elastic/elastic-agent/pull/5331) has a `skip-changelog` tag. I've added that PR into the features section but let me know if it shouldn't be there for any reason.

2024-11-05 22:15 UTC, cmacknz commented
The Helm chart being GA should definitely be in here, thanks

2024-11-06 14:18 UTC, kpollich requested changes

2024-11-06 14:18 UTC, kpollich commented on docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
> +* Advanced agent monitoring options UI for HTTP endpoint and diagnostics. {kibana-pull}193361[#193361]
```suggestion
* Add advanced agent monitoring options for HTTP endpoint and diagnostics. {kibana-pull}193361[#193361]
```

2024-11-06 14:18 UTC, kpollich commented on docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
> +* Enable feature flag for reusable integration policies. This feature allows you to create integrations policies that can be shared with multiple {agent} policies, thereby reducing the number of inte
```suggestion
* Add support for reusable/shareable integration policies. This feature allows you to create integrations policies that can be shared with multiple {agent} policies, thereby reducing the number of integrations policies that you need to actively manage. {kibana-pull}187153[#187153]
```

2024-11-06 14:18 UTC, kpollich commented on docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
> +* Support integration-level outputs. This feature enables you to send integration data to a specific output, over-writing the output defined in the {agent} Policy. {kibana-pull}189125[#189125]
```suggestion
* Add support for integration-level outputs. This feature enables you to send integration data to a specific output, overwriting the output defined in the {agent} Policy. {kibana-pull}189125[#189125]
```

2024-11-06 15:35 UTC, kilfoyle commented
Thanks @kpollich. I've added in all of your suggestions.

2024-11-06 16:01 UTC, kilfoyle commented
I've added a breaking change for Elastic Agent based (Beats [39993](https://github.com/elastic/beats/issues/39993)) as suggested by Luca [here](https://github.com/elastic/ingest-dev/issues/4013#issuecomment-2459754344).

2024-11-06 17:18 UTC, kpollich approved these changes
LGTM 🚀

2024-11-06 21:48 UTC, cmacknz approved these changes

2024-11-10 12:05 UTC, pierrehilbert approved these changes

2024-11-13 11:26 UTC, merged