Update docs to indicate that providers are no longer enabled by default
elastic/ingest-docs pull request #1530
Opened 2024-12-10 22:59 UTC by kilfoyle

This updates the Provider docs to indicate that providers are no longer enabled by default, as a result of https://github.com/elastic/elastic-agent/pull/6169

 - The main change is to [Configure providers for standalone Elastic Agent](https://www.elastic.co/guide/en/fleet/current/providers.html): 
    ![screen](https://github.com/user-attachments/assets/c3a1971b-68d5-49b3-bbd5-1e7bb8461b80)

 - I've also updated the [Kubernetes LeaderElection Provider](https://www.elastic.co/guide/en/fleet/current/kubernetes_leaderelection-provider.html)

 - I don't think any other providers pages need updating. The [Kubernetes provider](https://www.elastic.co/guide/en/fleet/current/kubernetes-provider.html) supports enabling individual resources (pods, nodes, or services), but I assume the defaults for that remain as is.

---

Closes: https://github.com/elastic/ingest-docs/issues/1529
Target: 8.18

2024-12-18 19:14 UTC, kilfoyle commented
@cmacknz @blakerouse  Would either of you mind reviewing this when you have a moment?

2024-12-23 16:03 UTC, blakerouse requested changes

2024-12-23 16:03 UTC, blakerouse commented on docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
> +Providers are disabled by default.
This is not correct.

```suggestion
Providers are automatically enabled if a provided is referenced in a policy.
```

2024-12-23 16:03 UTC, blakerouse commented on docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
> +Explicitly enable a provider by setting `enabled: true`.
Even this will not cause a provide to run. The provider must be referenced in the policy or it will not run.

2024-12-23 16:03 UTC, blakerouse commented on docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
> +Enable all providers by default and only disable explicitly configured providers by setting `agent.providers.initial_default: true`.
You should really keep this section how it was. As this still applies.

If you set `initial_default: false` and you have a provider referenced in the policy the provider still will not run.

2024-12-23 16:03 UTC, blakerouse commented on docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes_leaderelection-provider.asciidoc
> +set `enabled: true`.
Not true. It will turn on if anywhere in the policy references the `kubernetes_leaderelection`.

2025-01-02 18:33 UTC, kilfoyle commented on docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
> +Providers are disabled by default.
Changed to `Providers are enabled automatically if a provider is referenced in an {agent} policy.` via [7595bbc](https://github.com/elastic/ingest-docs/pull/1530/commits/7595bbc5b4f012b1cb9c87bdd2f60cd6b6d7b1cb)

2025-01-02 18:34 UTC, kilfoyle commented on docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
> +Explicitly enable a provider by setting `enabled: true`.
I removed the "Explicitly enable..." sentence.

2025-01-02 18:34 UTC, kilfoyle commented on docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
> +Enable all providers by default and only disable explicitly configured providers by setting `agent.providers.initial_default: true`.
Roger that. I've changed this back to the original.

2025-01-02 18:36 UTC, kilfoyle commented on docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes_leaderelection-provider.asciidoc
> +set `enabled: true`.
Changed to:

```
`enabled`:: (Optional) Defaults to false.
The LeaderElection provider is enabled automatically when the `kubernetes_leaderelection` is referenced anywhere in the {agemt} policy.
```

2025-01-02 18:36 UTC, kilfoyle commented
Thanks a lot @blakerouse! I've updated as you suggested.

2025-01-09 21:28 UTC, kilfoyle commented
@blakerouse  does this look okay to merge?

2025-01-10 20:44 UTC, blakerouse requested changes
Still some issues with it. See inline comments, hopefully it explains it better.

2025-01-10 20:44 UTC, blakerouse commented on docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
> +All registered providers are disabled by default.
```suggestion
All registered providers are disabled by default until they are referenced in a policy.
```

2025-01-10 20:44 UTC, blakerouse commented on docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
>  Disable all providers by default and only enable explicitly configured providers by setting `agent.providers.initial_default: false`.
```suggestion
You can disable all providers even if they are referenced in a policy by setting `agent.providers.initial_default: false`.
```

2025-01-10 20:44 UTC, blakerouse commented on docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
> -agent.providers.initial_default: false
I don't think this needs to be change.

2025-01-10 20:44 UTC, blakerouse commented on docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
> -    enabled: true
I don't think this needs to be change.

2025-01-10 20:44 UTC, blakerouse commented on docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
> -    enabled: true
You could possibly provide context on what this configuration is doing.

```
This disables all provides from running except for the docker provider (if it becomes referenced in the policy).
```

2025-01-10 20:44 UTC, blakerouse commented on docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes_leaderelection-provider.asciidoc
> -  #enabled: true
Don't change.

2025-01-10 20:44 UTC, blakerouse commented on docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes_leaderelection-provider.asciidoc
> -set `enabled: false`.
Don't change this.

It is still on, if its referenced. Setting to `enabled: false` would turn it off completely, even if it was referenced.

2025-01-10 21:27 UTC, blakerouse submitted a review, later dismissed
Looks good, except I think the headers of that section also need to be reverted. The section is still talking about disabling providers.

2025-01-10 21:27 UTC, blakerouse commented on docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
> +=== Enabling providers By default
```suggestion
=== Disabling Providers By Default
```

2025-01-10 21:27 UTC, blakerouse commented on docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
> +[[enable-providers-by-default]]
```suggestion
[[disable-providers-by-default]]
```

2025-01-20 15:27 UTC, merged