Adding info for conditions for autodiscovery
elastic/ingest-docs pull request #921
Opened 2024-02-15 12:59 UTC by gizas

Small section that adds some info for autodiscovery template definition for K8s

2024-02-15 14:24 UTC, kilfoyle commented on docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-conditions-autodiscover.asciidoc
> +IMPORTANT: Condition definintion is supported both in *{agent} by {fleet}* and in *standalone* scenarios.
```suggestion
IMPORTANT: Condition definintion is supported both in *{agent} managed by {fleet}* and in *standalone* scenarios.
```

2024-02-15 14:25 UTC, kilfoyle commented on docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-conditions-autodiscover.asciidoc
> +You can find available variables of autodiscovery in <<kubernetes-provider>>
```suggestion
For more information about variables and conditions in input configurations, refer to <<dynamic-input-configuration>>.
You can find available variables of autodiscovery in <<kubernetes-provider>>.
```
Just rephrasing a little bit to match what we have in some other docs.

2024-02-15 14:30 UTC, constanca-m approved these changes

2024-02-15 15:31 UTC, kilfoyle submitted a review, later dismissed
LGTM! 🚢

2024-02-15 17:04 UTC, gsantoro commented on docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-conditions-autodiscover.asciidoc
> +IMPORTANT: Condition definintion is supported both in *{agent} managed by {fleet}* and in *standalone* scenarios.
```suggestion
IMPORTANT: Condition definition is supported both in *{agent} managed by {fleet}* and in *standalone* scenarios.
```

2024-02-15 17:09 UTC, gsantoro requested changes
minor type

2024-02-19 08:26 UTC, gizas commented
@kilfoyle same issue I can not merge. So if you dont have any objection please ...

2024-02-19 10:17 UTC, gsantoro approved these changes

2024-02-20 14:09 UTC, merged